stages:
  - publish

publish:
  stage: publish
  only:
    refs:
      - main

  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --tag=$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME -f Dockerfile .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
